export const traducciones = {
    es: {
        inicio: "Inicio",
        destinos: "Destinos",
        consejos: "Consejos",
        perfil: "Perfil",
        contacto: "Contacto",
        iniciosesion: "Inicio sesion",
        registro: "Registro",
        español: "Español",
        ingles: "Inglés",
        banner1: "¡Descubre los mejores viajes!",
        banner2: "Mochileros Sin Fronteras",
        viena: "Viena, Austria",
        brujas: "Brujas, Bélgica",
        copenhague: "Copenhague, Dinamarca",
        liubliana: "Liubliana, Eslovenia",
        barcelona: "Barcelona, España",
        sevilla: "Sevilla, España",
        tallin: "Tallin, Estonia",
        paris: "París, Francia",
        comprar: "Comprar",
        praga: "Praga, República Checa",
        lucerna: "Lucerna, Suiza",
        reikiavik: "Reikiavik, Islandia",
        china: "Beijing, China",
        seul: "Seúl, Corea del Sur",
        jaipur: "Jaipur, India",
        politica: "Política de Privacidad",
        nosotros: "Sobre nosotros",
        ayuda: "Ayuda",
        cerrar_sesion: "Cerrar sesión",
        buscar: "Buscar destino o país...",
        continentes: "Todos los continentes",
        europa: "Europa",
        asia: "Asia",
        africa: "África",
        oceania: "Oceanía",
        america_norte: "América del Norte",
        america_sur: "América del Sur",
        avion: "Avión",
        tren: "Tren",
        autobus: "Autobús",
        barco: "Barco",
        consejos_comunidad: "Consejos de la comunidad:",
        consejos_escribir: "¡Escribe tu consejo!",
        titulo_consejo: "Título de consejo",
        descripcion_consejo: "Descripción del consejo",
        daltonismo: "Opción de daltonismo",
        oscuro: "Modo oscuro",
        pago: "Información de pago",
        pago1: "Premios y Monedero",
        pago2: "Métodos de pago",
        pago3: "Transacciones",
        cuenta: "Gestion de la cuenta",
        cuenta1: "Datos personales",
        cuenta2: "Ajustes de seguridad",
        cuenta3: "Mis consejos",
        preferencias: "Preferencias",
        preferencias1: "Opciones de personalización",
        preferencias2: "Preferencias de email",
        preferencias3: "Preferencias de teléfono",
        viajes: "Viajes",
        viajes1: "Mis reservas",
        viajes2: "Lista de favoritos",
        viajes3: "Mis viajes y reseñas",
        ayuda1: "Atención al Cliente",
        ayuda2: "Centro de seguridad",
        ayuda3: "Resolución de litigios",
        legal: "Información legal y privacidad",
        legal1: "Gestión de datos y privacidad",
        legal2: "Pautas sobre contenido",
        alojamiento: "Gestión de alojamientos",
        alojamiento1: "Da de alta tu alojamiento"
    },
    en: {
        inicio: "Home",
        destinos: "Destinations",
        consejos: "Tips",
        perfil: "Profile",
        contacto: "Contact",
        iniciosesion: "Log In",
        registro: "Sign Up",
        español: "Spanish",
        ingles: "English",
        banner1: "Discover the best trips!",
        banner2: "Backpackers Without Borders",
        viena: "Vienna, Austria",
        brujas: "Bruges, Belgium",
        copenhague: "Copenhagen, Denmark",
        liubliana: "Ljubljana, Slovenia",
        barcelona: "Barcelona, Spain",
        sevilla: "Seville, Spain",
        tallin: "Tallinn, Estonia",
        paris: "Paris, France",
        comprar: "Buy",
        praga: "Prague, Czech Republic",
        lucerna: "Lucerne, Switzerland",
        reikiavik: "Reykjavik, Iceland",
        china: "Beijing, China",
        seul: "Seoul, South Korea",
        jaipur: "Jaipur, India",
        politica: "Privacy Policy",
        nosotros: "About Us",
        ayuda: "Help",
        cerrar_sesion: "Log Out",
        buscar: "Search destination or country...",
        continentes: "All continents",
        europa: "Europe",
        asia: "Asia",
        africa: "Africa",
        oceania: "Oceania",
        america_norte: "North America",
        america_sur: "South America",
        avion: "Airplane",
        tren: "Train",
        autobus: "Bus",
        barco: "Boat",
        consejos_comunidad: "Community Tips:",
        consejos_escribir: "Write your tip!",
        titulo_consejo: "Tip title",
        descripcion_consejo: "Tip description",
        daltonismo: "Colorblind option",
        oscuro: "Dark mode",
        pago: "Payment Information",
        pago1: "Rewards and Wallet",
        pago2: "Payment Methods",
        pago3: "Transactions",
        cuenta: "Account Management",
        cuenta1: "Personal Data",
        cuenta2: "Security Settings",
        cuenta3: "My Tips",
        preferencias: "Preferences",
        preferencias1: "Customization Options",
        preferencias2: "Email Preferences",
        preferencias3: "Phone Preferences",
        viajes: "Trips",
        viajes1: "My Bookings",
        viajes2: "Favorites List",
        viajes3: "My Trips and Reviews",
        ayuda1: "Customer Service",
        ayuda2: "Safety Center",
        ayuda3: "Dispute Resolution",
        legal: "Legal and Privacy Information",
        legal1: "Data and Privacy Management",
        legal2: "Content Guidelines",
        alojamiento: "Accommodation Management",
        alojamiento1: "List your accommodation"
    }
};
