export const traducciones = {
    es: {
        inicio: "Inicio",
        destinos: "Destinos",
        consejos: "Consejos",
        perfil: "Perfil",
        contacto: "Contacto",
        iniciosesion: "Inicio sesion",
        registro: "Registro",
        español: "Español",
        ingles: "Inglés",
        banner1: "¡Descubre los mejores viajes!",
        banner2: "Mochileros Sin Fronteras",
        viena: "Viena, Austria",
        brujas: "Brujas, Bélgica",
        copenhague: "Copenhague, Dinamarca",
        liubliana: "Liubliana, Eslovenia",
        barcelona: "Barcelona, España",
        sevilla: "Sevilla, España",
        tallin: "Tallin, Estonia",
        paris: "París, Francia",
        comprar: "Comprar",
        praga: "Praga, República Checa",
        lucerna: "Lucerna, Suiza",
        reikiavik: "Reikiavik, Islandia",
        china: "China, Asia",
        seul: "Seúl, Corea del Sur",
        jaipur: "Jaipur, India",
        politica: "Política de Privacidad",
        nosotros: "Sobre nosotros",
        ayuda: "Ayuda",
        lista_deseados: "Lista de deseados:",
        sin_favoritos: "No tienes favoritos aún.",
        mis_reseñas: "Mis Reseñas",
        sin_reseñas: "No has escrito ninguna reseña.",
        filtrar_por: "Filtrar por:",
        todos: "Todos",
        europa: "Europa",
        asia: "Asia",
        africa: "África",
        oceania: "Oceanía",
        america_norte: "América del Norte",
        america_sur: "América del Sur",
        buscar: "Buscar destino o país...",
        precio: "Precio:",
        ver_detalles: "Ver detalles"
    },
    en: {
        inicio: "Home",
        destinos: "Destinations",
        consejos: "Tips",
        perfil: "Profile",
        contacto: "Contact",
        iniciosesion: "Log In",
        registro: "Sign Up",
        español: "Spanish",
        ingles: "English",
        banner1: "Discover the best trips!",
        banner2: "Backpackers Without Borders",
        viena: "Vienna, Austria",
        brujas: "Bruges, Belgium",
        copenhague: "Copenhagen, Denmark",
        liubliana: "Ljubljana, Slovenia",
        barcelona: "Barcelona, Spain",
        sevilla: "Seville, Spain",
        tallin: "Tallinn, Estonia",
        paris: "Paris, France",
        comprar: "Buy",
        praga: "Prague, Czech Republic",
        lucerna: "Lucerne, Switzerland",
        reikiavik: "Reykjavik, Iceland",
        china: "China, Asia",
        seul: "Seoul, South Korea",
        jaipur: "Jaipur, India",
        politica: "Privacy Policy",
        nosotros: "About Us",
        ayuda: "Help",
        lista_deseados: "Wishlist:",
        sin_favoritos: "You don't have any favorites yet.",
        mis_reseñas: "My Reviews",
        sin_reseñas: "You haven't written any reviews.",
        filtrar_por: "Filter by:",
        todos: "All",
        europa: "Europe",
        asia: "Asia",
        africa: "Africa",
        oceania: "Oceania",
        america_norte: "North America",
        america_sur: "South America",
        buscar: "Search destination or country...",
        precio: "Price:",
        ver_detalles: "View details"
    }
};
